package org.nekomanga.presentation.theme.schemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object EmeraldBrightColorScheme : BaseColorScheme() {
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF69FFA3),
            onPrimary = Color(0xFF00391C),
            primaryContainer = Color(0xFF33D37D),
            onPrimaryContainer = Color(0xFF00351A),
            secondary = Color(0xFF69FFA3),
            onSecondary = Color(0xFF00391C),
            secondaryContainer = Color(0xFF33D37D),
            onSecondaryContainer = Color(0xFF00351A),
            tertiary = Color(0xFF60DE8C),
            onTertiary = Color(0xFF00391A),
            tertiaryContainer = Color(0xFF008646),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF0E150F),
            onBackground = Color(0xFFDCE5DB),
            surface = Color(0xFF141313),
            onSurface = Color(0xFFE5E2E1),
            surfaceVariant = Color(0xFF3C4A3F),
            onSurfaceVariant = Color(0xFFBBCABC),
            outline = Color(0xFF869487),
            outlineVariant = Color(0xFF3C4A3F),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE5E2E1),
            inverseOnSurface = Color(0xFF313030),
            inversePrimary = Color(0xFF006D3B),
            surfaceDim = Color(0xFF141313),
            surfaceBright = Color(0xFF3A3939),
            surfaceContainerLowest = Color(0xFF0E0E0E),
            surfaceContainerLow = Color(0xFF1C1B1B),
            surfaceContainer = Color(0xFF201F1F),
            surfaceContainerHigh = Color(0xFF2B2A2A),
            surfaceContainerHighest = Color(0xFF353434),
        )
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF006D3B),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF4AE48C),
            onPrimaryContainer = Color(0xFF004221),
            secondary = Color(0xFF006D3B),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFF4AE48C),
            onSecondaryContainer = Color(0xFF004221),
            tertiary = Color(0xFF006D38),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF34B76A),
            onTertiaryContainer = Color(0xFF001B09),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFF3FCF1),
            onBackground = Color(0xFF161D17),
            surface = Color(0xFFFDF8F8),
            onSurface = Color(0xFF1C1B1B),
            surfaceVariant = Color(0xFFD7E7D7),
            onSurfaceVariant = Color(0xFF3C4A3F),
            outline = Color(0xFF6C7B6E),
            outlineVariant = Color(0xFFBBCABC),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF313030),
            inverseOnSurface = Color(0xFFF4F0EF),
            inversePrimary = Color(0xFF46E189),
            surfaceDim = Color(0xFFDDD9D8),
            surfaceBright = Color(0xFFFDF8F8),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF7F3F2),
            surfaceContainer = Color(0xFFF1EDEC),
            surfaceContainerHigh = Color(0xFFEBE7E7),
            surfaceContainerHighest = Color(0xFFE5E2E1),
        )
}
