package org.nekomanga.presentation.theme.schemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object FlatLimeColorScheme : BaseColorScheme() {
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF006D38),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF63C983),
            onPrimaryContainer = Color(0xFF003015),
            secondary = Color(0xFF006D2F),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFF33B55C),
            onSecondaryContainer = Color(0xFF001705),
            tertiary = Color(0xFF003D18),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF1E6233),
            onTertiaryContainer = Color(0xFFEDFFEB),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFF6FBF2),
            onBackground = Color(0xFF171D18),
            surface = Color(0xFFFCF9F9),
            onSurface = Color(0xFF1B1B1C),
            surfaceVariant = Color(0xFFE1E2E7),
            onSurfaceVariant = Color(0xFF44474B),
            outline = Color(0xFF75777B),
            outlineVariant = Color(0xFFC5C6CB),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF303031),
            inverseOnSurface = Color(0xFFF3F0F0),
            inversePrimary = Color(0xFF75DB94),
            surfaceDim = Color(0xFFDCD9DA),
            surfaceBright = Color(0xFFFCF9F9),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF6F3F3),
            surfaceContainer = Color(0xFFF0EDEE),
            surfaceContainerHigh = Color(0xFFEAE7E8),
            surfaceContainerHighest = Color(0xFFE4E2E2),
        )

    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFF79DF98),
            onPrimary = Color(0xFF00391A),
            primaryContainer = Color(0xFF4FB572),
            onPrimaryContainer = Color(0xFF001B09),
            secondary = Color(0xFF61DF80),
            onSecondary = Color(0xFF003915),
            secondaryContainer = Color(0xFF00873C),
            onSecondaryContainer = Color(0xFFFFFFFF),
            tertiary = Color(0xFF91D69B),
            onTertiary = Color(0xFF003916),
            tertiaryContainer = Color(0xFF00461D),
            onTertiaryContainer = Color(0xFF99DFA3),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF0F1510),
            onBackground = Color(0xFFDFE4DC),
            surface = Color(0xFF131314),
            onSurface = Color(0xFFE4E2E2),
            surfaceVariant = Color(0xFF44474B),
            onSurfaceVariant = Color(0xFFC5C6CB),
            outline = Color(0xFF8E9195),
            outlineVariant = Color(0xFF44474B),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE4E2E2),
            inverseOnSurface = Color(0xFF303031),
            inversePrimary = Color(0xFF006D38),
            surfaceDim = Color(0xFF131314),
            surfaceBright = Color(0xFF39393A),
            surfaceContainerLowest = Color(0xFF0E0E0F),
            surfaceContainerLow = Color(0xFF1B1B1C),
            surfaceContainer = Color(0xFF1F1F20),
            surfaceContainerHigh = Color(0xFF2A2A2A),
            surfaceContainerHighest = Color(0xFF353535)
        )
}
