package org.nekomanga.presentation.theme.schemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object GreyWolfColorScheme : BaseColorScheme() {
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFC8C6C6),
            onPrimary = Color(0xFF303030),
            primaryContainer = Color(0xFF373737),
            onPrimaryContainer = Color(0xFFC9C7C7),
            secondary = Color(0xFFC8C6C5),
            onSecondary = Color(0xFF313030),
            secondaryContainer = Color(0xFF403F3F),
            onSecondaryContainer = Color(0xFFD6D3D3),
            tertiary = Color(0xFFC9C6C5),
            onTertiary = Color(0xFF313030),
            tertiaryContainer = Color(0xFF383737),
            onTertiaryContainer = Color(0xFFCAC7C7),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF141313),
            onBackground = Color(0xFFE5E2E1),
            surface = Color(0xFF141313),
            onSurface = Color(0xFFE5E2E1),
            surfaceVariant = Color(0xFF444748),
            onSurfaceVariant = Color(0xFFC4C7C7),
            outline = Color(0xFF8E9192),
            outlineVariant = Color(0xFF444748),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE5E2E1),
            inverseOnSurface = Color(0xFF313030),
            inversePrimary = Color(0xFF5F5E5E),
            surfaceDim = Color(0xFF141313),
            surfaceBright = Color(0xFF3A3939),
            surfaceContainerLowest = Color(0xFF0E0E0E),
            surfaceContainerLow = Color(0xFF1C1B1B),
            surfaceContainer = Color(0xFF201F1F),
            surfaceContainerHigh = Color(0xFF2B2A2A),
            surfaceContainerHighest = Color(0xFF353434),
        )

    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF2D2D2D),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF4F4F4F),
            onPrimaryContainer = Color(0xFFF0EEED),
            secondary = Color(0xFF5F5E5E),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFE9E6E5),
            onSecondaryContainer = Color(0xFF4B4A4A),
            tertiary = Color(0xFF2E2D2D),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF504F4F),
            onTertiaryContainer = Color(0xFFF2EEED),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFDF8F8),
            onBackground = Color(0xFF1C1B1B),
            surface = Color(0xFFFDF8F8),
            onSurface = Color(0xFF1C1B1B),
            surfaceVariant = Color(0xFFE0E3E3),
            onSurfaceVariant = Color(0xFF444748),
            outline = Color(0xFF747878),
            outlineVariant = Color(0xFFC4C7C7),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF313030),
            inverseOnSurface = Color(0xFFF4F0EF),
            inversePrimary = Color(0xFFC8C6C6),
            surfaceDim = Color(0xFFDDD9D8),
            surfaceBright = Color(0xFFFDF8F8),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF7F3F2),
            surfaceContainer = Color(0xFFF1EDEC),
            surfaceContainerHigh = Color(0xFFEBE7E7),
            surfaceContainerHighest = Color(0xFFE5E2E1),
        )
}
