package org.nekomanga.presentation.theme.schemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object LavenderColorScheme : BaseColorScheme() {
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFDDB8FF),
            onPrimary = Color(0xFF49037E),
            primaryContainer = Color(0xFF925AC8),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFFDDB8FF),
            onSecondary = Color(0xFF48087B),
            secondaryContainer = Color(0xFF713CA5),
            onSecondaryContainer = Color(0xFFFFFBFF),
            tertiary = Color(0xFFFFFFFF),
            onTertiary = Color(0xFF332D43),
            tertiaryContainer = Color(0xFFDAD0EC),
            onTertiaryContainer = Color(0xFF433C52),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF161219),
            onBackground = Color(0xFFE9E0EA),
            surface = Color(0xFF161219),
            onSurface = Color(0xFFE9E0EA),
            surfaceVariant = Color(0xFF4C4451),
            onSurfaceVariant = Color(0xFFCEC3D3),
            outline = Color(0xFF978D9C),
            outlineVariant = Color(0xFF4C4451),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE9E0EA),
            inverseOnSurface = Color(0xFF332F36),
            inversePrimary = Color(0xFF7A43B0),
            surfaceDim = Color(0xFF161219),
            surfaceBright = Color(0xFF3C373F),
            surfaceContainerLowest = Color(0xFF100D13),
            surfaceContainerLow = Color(0xFF1E1A21),
            surfaceContainer = Color(0xFF221E25),
            surfaceContainerHigh = Color(0xFF2D2830),
            surfaceContainerHighest = Color(0xFF38333B),
        )
    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF6B33A0),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF925AC8),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFF642E97),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFF8B55BF),
            onSecondaryContainer = Color(0xFFFFFFFF),
            tertiary = Color(0xFF625B73),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFFF0E6FF),
            onTertiaryContainer = Color(0xFF504960),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFFFF7FE),
            onBackground = Color(0xFF1E1A21),
            surface = Color(0xFFFFF7FE),
            onSurface = Color(0xFF1E1A21),
            surfaceVariant = Color(0xFFEBDEEF),
            onSurfaceVariant = Color(0xFF4C4451),
            outline = Color(0xFF7D7482),
            outlineVariant = Color(0xFFCEC3D3),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF332F36),
            inverseOnSurface = Color(0xFFF7EEF8),
            inversePrimary = Color(0xFFDDB8FF),
            surfaceDim = Color(0xFFE0D7E1),
            surfaceBright = Color(0xFFFFF7FE),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFAF1FB),
            surfaceContainer = Color(0xFFF4EBF5),
            surfaceContainerHigh = Color(0xFFEEE5EF),
            surfaceContainerHighest = Color(0xFFE9E0EA),
        )
}
