package org.nekomanga.presentation.theme.schemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object SapphireDuskTealOcean : BaseColorScheme() {
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFA2DAF4),
            onPrimary = Color(0xFF003545),
            primaryContainer = Color(0xFF79B1CA),
            onPrimaryContainer = Color(0xFF00222D),
            secondary = Color(0xFF8ECFEF),
            onSecondary = Color(0xFF003547),
            secondaryContainer = Color(0xFF377C99),
            onSecondaryContainer = Color(0xFFFFFFFF),
            tertiary = Color(0xFFFFFFFF),
            onTertiary = Color(0xFF003543),
            tertiaryContainer = Color(0xFFA7DDF0),
            onTertiaryContainer = Color(0xFF004656),
            error = Color(0xFFFFB4AB),
            onError = Color(0xFF690005),
            errorContainer = Color(0xFF93000A),
            onErrorContainer = Color(0xFFFFDAD6),
            background = Color(0xFF111415),
            onBackground = Color(0xFFE1E2E4),
            surface = Color(0xFF131313),
            onSurface = Color(0xFFE5E2E1),
            surfaceVariant = Color(0xFF434749),
            onSurfaceVariant = Color(0xFFC4C7C9),
            outline = Color(0xFF8E9193),
            outlineVariant = Color(0xFF434749),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFE5E2E1),
            inverseOnSurface = Color(0xFF313030),
            inversePrimary = Color(0xFF29657C),
            surfaceDim = Color(0xFF131313),
            surfaceBright = Color(0xFF3A3939),
            surfaceContainerLowest = Color(0xFF0E0E0E),
            surfaceContainerLow = Color(0xFF1C1B1C),
            surfaceContainer = Color(0xFF201F20),
            surfaceContainerHigh = Color(0xFF2A2A2A),
            surfaceContainerHighest = Color(0xFF353535),
        )

    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF296863),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFF6CA9A2),
            onPrimaryContainer = Color(0xFF001412),
            secondary = Color(0xFF006A62),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFF29BDB0),
            onSecondaryContainer = Color(0xFF002421),
            tertiary = Color(0xFF003E38),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF27625B),
            onTertiaryContainer = Color(0xFFFFFFFF),
            error = Color(0xFFBA1A1A),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFDAD6),
            onErrorContainer = Color(0xFF410002),
            background = Color(0xFFF8FAF8),
            onBackground = Color(0xFF191C1C),
            surface = Color(0xFFF8FAF8),
            onSurface = Color(0xFF191C1C),
            surfaceVariant = Color(0xFFDBE5E2),
            onSurfaceVariant = Color(0xFF3F4947),
            outline = Color(0xFF6F7977),
            outlineVariant = Color(0xFFBFC8C6),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF2E3130),
            inverseOnSurface = Color(0xFFEFF1F0),
            inversePrimary = Color(0xFF94D2CB),
            surfaceDim = Color(0xFFD8DAD9),
            surfaceBright = Color(0xFFF8FAF8),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFF2F4F2),
            surfaceContainer = Color(0xFFECEEED),
            surfaceContainerHigh = Color(0xFFE7E9E7),
            surfaceContainerHighest = Color(0xFFE1E3E1),
        )
}
