package org.nekomanga.presentation.theme.schemes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object StrawberriesColorScheme : BaseColorScheme() {
    override val darkScheme =
        darkColorScheme(
            primary = Color(0xFFFFB3B3),
            onPrimary = Color(0xFF680015),
            primaryContainer = Color(0xFFC70F34),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFFFFB2B8),
            onSecondary = Color(0xFF67001D),
            secondaryContainer = Color(0xFFD53855),
            onSecondaryContainer = Color(0xFFFFFFFF),
            tertiary = Color(0xFFFFB3B5),
            onTertiary = Color(0xFF630C1C),
            tertiaryContainer = Color(0xFF5C0618),
            onTertiaryContainer = Color(0xFFFF9DA2),
            error = Color(0xFFFFD5A1),
            onError = Color(0xFF452B00),
            errorContainer = Color(0xFFF3A200),
            onErrorContainer = Color(0xFF392300),
            background = Color(0xFF1F0F0F),
            onBackground = Color(0xFFFADBDB),
            surface = Color(0xFF1F0F0F),
            onSurface = Color(0xFFFADBDB),
            surfaceVariant = Color(0xFF5C4040),
            onSurfaceVariant = Color(0xFFE4BDBD),
            outline = Color(0xFFAB8888),
            outlineVariant = Color(0xFF5C4040),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFFFADBDB),
            inverseOnSurface = Color(0xFF3E2C2C),
            inversePrimary = Color(0xFFBE022F),
            surfaceDim = Color(0xFF1F0F0F),
            surfaceBright = Color(0xFF483434),
            surfaceContainerLowest = Color(0xFF190A0A),
            surfaceContainerLow = Color(0xFF281717),
            surfaceContainer = Color(0xFF2C1B1B),
            surfaceContainerHigh = Color(0xFF372525),
            surfaceContainerHighest = Color(0xFF433030),
        )

    override val lightScheme =
        lightColorScheme(
            primary = Color(0xFF950022),
            onPrimary = Color(0xFFFFFFFF),
            primaryContainer = Color(0xFFD31D3B),
            onPrimaryContainer = Color(0xFFFFFFFF),
            secondary = Color(0xFFA10833),
            onSecondary = Color(0xFFFFFFFF),
            secondaryContainer = Color(0xFFD53855),
            onSecondaryContainer = Color(0xFFFFFFFF),
            tertiary = Color(0xFF4C0010),
            onTertiary = Color(0xFFFFFFFF),
            tertiaryContainer = Color(0xFF7C202C),
            onTertiaryContainer = Color(0xFFFFCCCD),
            error = Color(0xFF825500),
            onError = Color(0xFFFFFFFF),
            errorContainer = Color(0xFFFFB239),
            onErrorContainer = Color(0xFF482D00),
            background = Color(0xFFFFF8F7),
            onBackground = Color(0xFF281717),
            surface = Color(0xFFFFF8F7),
            onSurface = Color(0xFF281717),
            surfaceVariant = Color(0xFFFFDAD9),
            onSurfaceVariant = Color(0xFF5C4040),
            outline = Color(0xFF906F6F),
            outlineVariant = Color(0xFFE4BDBD),
            scrim = Color(0xFF000000),
            inverseSurface = Color(0xFF3E2C2C),
            inverseOnSurface = Color(0xFFFFEDEC),
            inversePrimary = Color(0xFFFFB3B3),
            surfaceDim = Color(0xFFF1D3D2),
            surfaceBright = Color(0xFFFFF8F7),
            surfaceContainerLowest = Color(0xFFFFFFFF),
            surfaceContainerLow = Color(0xFFFFF0EF),
            surfaceContainer = Color(0xFFFFE9E8),
            surfaceContainerHigh = Color(0xFFFFE1E1),
            surfaceContainerHighest = Color(0xFFFADBDB),
        )
}
